/**
 * Application route paths constants
 */
export const PATHS = {
  HOME: '/',
  MARKETS: '/markets',
  MARKET_DETAIL: '/markets/:id',
  FARMERS: '/farmers',
  FARMER_DETAIL: '/farmers/:id',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  ABOUT: '/about',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  UNAUTHORIZED: '/unauthorized',
  // Authenticated role roots
  BUYER: '/buyer',
  BUYER_PRODUCTS: '/buyer/products',
  BUYER_PRODUCT_DETAIL: '/buyer/products/:id',
  BUYER_FARMERS: '/buyer/farmers',
  BUYER_FARMER_DETAIL: '/buyer/farmers/:id',
  BUYER_MARKETS: '/buyer/markets',
  BUYER_MARKET_DETAIL: '/buyer/markets/:id',
  BUYER_CART: '/buyer/cart',
  BUYER_ORDER_CONFIRMED: '/buyer/order-confirmed',
  BUYER_ORDERS: '/buyer/orders',
  BUYER_ORDER_DETAIL: '/buyer/orders/:id',
  BUYER_FAVORITES: '/buyer/favorites',
  BUYER_ASSISTANT: '/buyer/assistant',
  BUYER_PROFILE: '/buyer/profile',
  BUYER_PROFILE_DETAILS: '/buyer/profile/details',
  BUYER_PROFILE_MARKETS: '/buyer/profile/markets',
  BUYER_PROFILE_NOTIFICATIONS: '/buyer/profile/notifications',
  BUYER_PROFILE_HELP: '/buyer/profile/help',
  BUYER_REVIEWS: '/buyer/reviews',
  BUYER_NOTIFICATIONS: '/buyer/notifications',
  VENDOR: '/vendor',
  ADMIN: '/admin',
};


